/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingResponse } from '../../models/booking-response';
import { CancelRequest } from '../../models/cancel-request';

export interface Cancel1$Params {
  id: string;
  body?: CancelRequest;
}

export function cancel1(
  http: HttpClient,
  rootUrl: string,
  params: Cancel1$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BookingResponse>> {
  const rb = new RequestBuilder(rootUrl, cancel1.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingResponse>;
    }),
  );
}

cancel1.PATH = '/api/admin/bookings/{id}/cancel';
