/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingResponse } from '../../models/booking-response';

export interface Get6$Params {
  id: string;
}

export function get6(
  http: HttpClient,
  rootUrl: string,
  params: Get6$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BookingResponse>> {
  const rb = new RequestBuilder(rootUrl, get6.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingResponse>;
    }),
  );
}

get6.PATH = '/api/admin/bookings/{id}';
