/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageBookingResponse } from '../../models/page-booking-response';

export interface List8$Params {
  status?: 'PENDING_PAYMENT' | 'CONFIRMED' | 'ACTIVATED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
  customerId?: string;
  vehicleId?: string;
  pageable: Pageable;
}

export function list8(
  http: HttpClient,
  rootUrl: string,
  params: List8$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageBookingResponse>> {
  const rb = new RequestBuilder(rootUrl, list8.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('customerId', params.customerId, {});
    rb.query('vehicleId', params.vehicleId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageBookingResponse>;
    }),
  );
}

list8.PATH = '/api/admin/bookings';
