/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateVehicleRequest } from '../../models/create-vehicle-request';
import { VehicleResponse } from '../../models/vehicle-response';

export interface Create2$Params {
  body: CreateVehicleRequest;
}

export function create2(
  http: HttpClient,
  rootUrl: string,
  params: Create2$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VehicleResponse>> {
  const rb = new RequestBuilder(rootUrl, create2.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleResponse>;
    }),
  );
}

create2.PATH = '/api/admin/vehicles';
