/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleResponse } from '../../models/vehicle-response';

export interface Get2$Params {
  id: string;
}

export function get2(
  http: HttpClient,
  rootUrl: string,
  params: Get2$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VehicleResponse>> {
  const rb = new RequestBuilder(rootUrl, get2.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleResponse>;
    }),
  );
}

get2.PATH = '/api/admin/vehicles/{id}';
