/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageVehicleResponse } from '../../models/page-vehicle-response';

export interface List3$Params {
  status?:
    | 'AVAILABLE'
    | 'RESERVED'
    | 'IN_PREPARATION'
    | 'EN_ROUTE_TO_CUSTOMER'
    | 'WITH_CUSTOMER'
    | 'EN_ROUTE_TO_WAREHOUSE'
    | 'AWAITING_INSPECTION'
    | 'IN_CLEANING'
    | 'IN_MAINTENANCE'
    | 'OUT_OF_SERVICE'
    | 'RETIRED';
  classId?: string;
  zoneId?: string;
  pageable: Pageable;
}

export function list3(
  http: HttpClient,
  rootUrl: string,
  params: List3$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageVehicleResponse>> {
  const rb = new RequestBuilder(rootUrl, list3.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('classId', params.classId, {});
    rb.query('zoneId', params.zoneId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageVehicleResponse>;
    }),
  );
}

list3.PATH = '/api/admin/vehicles';
