/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransitionStatusRequest } from '../../models/transition-status-request';
import { VehicleResponse } from '../../models/vehicle-response';

export interface Transition$Params {
  id: string;
  body: TransitionStatusRequest;
}

export function transition(
  http: HttpClient,
  rootUrl: string,
  params: Transition$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VehicleResponse>> {
  const rb = new RequestBuilder(rootUrl, transition.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleResponse>;
    }),
  );
}

transition.PATH = '/api/admin/vehicles/{id}/status';
