/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateVehicleClassRequest } from '../../models/update-vehicle-class-request';
import { VehicleClassResponse } from '../../models/vehicle-class-response';

export interface Update3$Params {
  id: string;
  body: UpdateVehicleClassRequest;
}

export function update3(
  http: HttpClient,
  rootUrl: string,
  params: Update3$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VehicleClassResponse>> {
  const rb = new RequestBuilder(rootUrl, update3.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleClassResponse>;
    }),
  );
}

update3.PATH = '/api/admin/vehicle-classes/{id}';
