/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailableClassResponse } from '../../models/available-class-response';

export interface Available$Params {
  pickupAt: string;
  dropoffAt: string;
  pickupLat: number;
  pickupLng: number;
}

export function available(
  http: HttpClient,
  rootUrl: string,
  params: Available$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<AvailableClassResponse>>> {
  const rb = new RequestBuilder(rootUrl, available.PATH, 'get');
  if (params) {
    rb.query('pickupAt', params.pickupAt, {});
    rb.query('dropoffAt', params.dropoffAt, {});
    rb.query('pickupLat', params.pickupLat, {});
    rb.query('pickupLng', params.pickupLng, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AvailableClassResponse>>;
    }),
  );
}

available.PATH = '/api/customer/vehicles/available';
