/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleClassResponse } from '../../models/vehicle-class-response';

export interface Classes$Params {}

export function classes(
  http: HttpClient,
  rootUrl: string,
  params?: Classes$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<VehicleClassResponse>>> {
  const rb = new RequestBuilder(rootUrl, classes.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VehicleClassResponse>>;
    }),
  );
}

classes.PATH = '/api/customer/vehicle-classes';
