/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZoneContainsResponse } from '../../models/zone-contains-response';

export interface Contains$Params {
  lat: number;
  lng: number;
}

export function contains(
  http: HttpClient,
  rootUrl: string,
  params: Contains$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ZoneContainsResponse>> {
  const rb = new RequestBuilder(rootUrl, contains.PATH, 'get');
  if (params) {
    rb.query('lat', params.lat, {});
    rb.query('lng', params.lng, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZoneContainsResponse>;
    }),
  );
}

contains.PATH = '/api/zones/contains';
