/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicZoneResponse } from '../../models/public-zone-response';

export interface PublicZones$Params {}

export function publicZones(
  http: HttpClient,
  rootUrl: string,
  params?: PublicZones$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<PublicZoneResponse>>> {
  const rb = new RequestBuilder(rootUrl, publicZones.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PublicZoneResponse>>;
    }),
  );
}

publicZones.PATH = '/api/customer/zones';
