/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InspectionResponse } from '../../models/inspection-response';

export interface Get4$Params {
  id: string;
}

export function get4(
  http: HttpClient,
  rootUrl: string,
  params: Get4$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<InspectionResponse>> {
  const rb = new RequestBuilder(rootUrl, get4.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InspectionResponse>;
    }),
  );
}

get4.PATH = '/api/admin/inspections/{id}';
