/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageTripResponse } from '../../models/page-trip-response';

export interface List5$Params {
  status?: 'IN_PROGRESS' | 'ENDED_PENDING_INSPECTION' | 'CLOSED';
  customerId?: string;
  pageable: Pageable;
}

export function list5(
  http: HttpClient,
  rootUrl: string,
  params: List5$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageTripResponse>> {
  const rb = new RequestBuilder(rootUrl, list5.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('customerId', params.customerId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageTripResponse>;
    }),
  );
}

list5.PATH = '/api/admin/trips';
