/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InspectionResponse } from '../../models/inspection-response';
import { ReviewRequest } from '../../models/review-request';

export interface Review$Params {
  id: string;
  body: ReviewRequest;
}

export function review(
  http: HttpClient,
  rootUrl: string,
  params: Review$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<InspectionResponse>> {
  const rb = new RequestBuilder(rootUrl, review.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InspectionResponse>;
    }),
  );
}

review.PATH = '/api/admin/inspections/{id}/review';
