/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageBookingResponse } from '../../models/page-booking-response';

export interface List1$Params {
  pageable: Pageable;
}

export function list1(
  http: HttpClient,
  rootUrl: string,
  params: List1$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageBookingResponse>> {
  const rb = new RequestBuilder(rootUrl, list1.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageBookingResponse>;
    }),
  );
}

list1.PATH = '/api/customer/bookings';
