/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuoteRequest } from '../../models/quote-request';
import { QuoteResponse } from '../../models/quote-response';

export interface Quote$Params {
  body: QuoteRequest;
}

export function quote(
  http: HttpClient,
  rootUrl: string,
  params: Quote$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<QuoteResponse>> {
  const rb = new RequestBuilder(rootUrl, quote.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuoteResponse>;
    }),
  );
}

quote.PATH = '/api/customer/bookings/quote';
