/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePromoRequest } from '../../models/create-promo-request';
import { PromoResponse } from '../../models/promo-response';

export interface CreatePromo$Params {
  body: CreatePromoRequest;
}

export function createPromo(
  http: HttpClient,
  rootUrl: string,
  params: CreatePromo$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PromoResponse>> {
  const rb = new RequestBuilder(rootUrl, createPromo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromoResponse>;
    }),
  );
}

createPromo.PATH = '/api/admin/pricing/promos';
