/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRateRequest } from '../../models/create-rate-request';
import { RateResponse } from '../../models/rate-response';

export interface CreateRate$Params {
  body: CreateRateRequest;
}

export function createRate(
  http: HttpClient,
  rootUrl: string,
  params: CreateRate$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<RateResponse>> {
  const rb = new RequestBuilder(rootUrl, createRate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RateResponse>;
    }),
  );
}

createRate.PATH = '/api/admin/pricing/rates';
