/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateZoneRequest } from '../../models/create-zone-request';
import { ZoneResponse } from '../../models/zone-response';

export interface Create1$Params {
  body: CreateZoneRequest;
}

export function create1(
  http: HttpClient,
  rootUrl: string,
  params: Create1$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ZoneResponse>> {
  const rb = new RequestBuilder(rootUrl, create1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZoneResponse>;
    }),
  );
}

create1.PATH = '/api/admin/zones';
