/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginRequest } from '../../models/login-request';
import { StaffProfileResponse } from '../../models/staff-profile-response';

export interface Login1$Params {
  body: LoginRequest;
}

export function login1(
  http: HttpClient,
  rootUrl: string,
  params: Login1$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<StaffProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, login1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffProfileResponse>;
    }),
  );
}

login1.PATH = '/api/admin/auth/login';
