/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetHealth$Params as GetHealth$Params } from './fn/health/get-health';
export { getHealth as getHealth } from './fn/health/get-health';
export type { ListVehicleClasses$Params as ListVehicleClasses$Params } from './fn/vehicle-classes/list-vehicle-classes';
export { listVehicleClasses as listVehicleClasses } from './fn/vehicle-classes/list-vehicle-classes';
