/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { Api } from './api';

export type { HealthStatus } from './models/health-status';
export type { VehicleClass } from './models/vehicle-class';

export type { GetHealth$Params as GetHealth$Params } from './fn/health/get-health';
export { getHealth as getHealth } from './fn/health/get-health';
export type { ListVehicleClasses$Params as ListVehicleClasses$Params } from './fn/vehicle-classes/list-vehicle-classes';
export { listVehicleClasses as listVehicleClasses } from './fn/vehicle-classes/list-vehicle-classes';
