/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageTripResponse } from '../../models/page-trip-response';

export interface History$Params {
  pageable: Pageable;
}

export function history(
  http: HttpClient,
  rootUrl: string,
  params: History$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageTripResponse>> {
  const rb = new RequestBuilder(rootUrl, history.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageTripResponse>;
    }),
  );
}

history.PATH = '/api/customer/me/trips';
