/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerReportRequest } from '../../models/customer-report-request';
import { IncidentResponse } from '../../models/incident-response';

export interface Report$Params {
  id: string;
  body: CustomerReportRequest;
}

export function report(
  http: HttpClient,
  rootUrl: string,
  params: Report$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<IncidentResponse>> {
  const rb = new RequestBuilder(rootUrl, report.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncidentResponse>;
    }),
  );
}

report.PATH = '/api/customer/me/trips/{id}/incidents';
