/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InspectionResponse } from '../../models/inspection-response';
import { SubmitInspectionRequest } from '../../models/submit-inspection-request';

export interface Submit$Params {
  id: string;
  phase: 'PICKUP' | 'DROPOFF';
  body: SubmitInspectionRequest;
}

export function submit(
  http: HttpClient,
  rootUrl: string,
  params: Submit$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<InspectionResponse>> {
  const rb = new RequestBuilder(rootUrl, submit.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('phase', params.phase, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InspectionResponse>;
    }),
  );
}

submit.PATH = '/api/customer/me/trips/{id}/inspections/{phase}';
