/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadUrlRequest } from '../../models/upload-url-request';
import { UploadUrlResponse } from '../../models/upload-url-response';

export interface UploadUrl$Params {
  id: string;
  phase: 'PICKUP' | 'DROPOFF';
  body: UploadUrlRequest;
}

export function uploadUrl(
  http: HttpClient,
  rootUrl: string,
  params: UploadUrl$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<UploadUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadUrl.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('phase', params.phase, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadUrlResponse>;
    }),
  );
}

uploadUrl.PATH = '/api/customer/me/trips/{id}/inspections/{phase}/upload-url';
