/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageAdminCustomerSummary } from '../../models/page-admin-customer-summary';

export interface List7$Params {
  email?: string;
  phone?: string;
  verificationStatus?: 'UNVERIFIED' | 'IN_PROGRESS' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
  status?: 'ACTIVE' | 'SUSPENDED' | 'DEACTIVATED';
  pageable: Pageable;
}

export function list7(
  http: HttpClient,
  rootUrl: string,
  params: List7$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageAdminCustomerSummary>> {
  const rb = new RequestBuilder(rootUrl, list7.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
    rb.query('phone', params.phone, {});
    rb.query('verificationStatus', params.verificationStatus, {});
    rb.query('status', params.status, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageAdminCustomerSummary>;
    }),
  );
}

list7.PATH = '/api/admin/customers';
