/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminCustomerDetail } from '../../models/admin-customer-detail';
import { UpdateCustomerStatusRequest } from '../../models/update-customer-status-request';

export interface UpdateStatus$Params {
  id: string;
  body: UpdateCustomerStatusRequest;
}

export function updateStatus(
  http: HttpClient,
  rootUrl: string,
  params: UpdateStatus$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AdminCustomerDetail>> {
  const rb = new RequestBuilder(rootUrl, updateStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminCustomerDetail>;
    }),
  );
}

updateStatus.PATH = '/api/admin/customers/{id}';
