/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncidentResponse } from '../../models/incident-response';
import { StaffCreateRequest } from '../../models/staff-create-request';

export interface Create4$Params {
  body: StaffCreateRequest;
}

export function create4(
  http: HttpClient,
  rootUrl: string,
  params: Create4$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<IncidentResponse>> {
  const rb = new RequestBuilder(rootUrl, create4.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncidentResponse>;
    }),
  );
}

create4.PATH = '/api/admin/incidents';
