/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageIncidentResponse } from '../../models/page-incident-response';

export interface List6$Params {
  status?: 'OPEN' | 'IN_REVIEW' | 'RESOLVED' | 'DISMISSED';
  type?: 'DAMAGE' | 'OUT_OF_ZONE' | 'LATE_RETURN' | 'ACCIDENT' | 'TICKET' | 'OTHER';
  tripId?: string;
  pageable: Pageable;
}

export function list6(
  http: HttpClient,
  rootUrl: string,
  params: List6$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageIncidentResponse>> {
  const rb = new RequestBuilder(rootUrl, list6.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('tripId', params.tripId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageIncidentResponse>;
    }),
  );
}

list6.PATH = '/api/admin/incidents';
