/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncidentResponse } from '../../models/incident-response';
import { UpdateIncidentRequest } from '../../models/update-incident-request';

export interface Update4$Params {
  id: string;
  body: UpdateIncidentRequest;
}

export function update4(
  http: HttpClient,
  rootUrl: string,
  params: Update4$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<IncidentResponse>> {
  const rb = new RequestBuilder(rootUrl, update4.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncidentResponse>;
    }),
  );
}

update4.PATH = '/api/admin/incidents/{id}';
