/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressRequest {
  city: string;
  country?: string;
  isDefault?: boolean;
  label?: string;
  lat: number;
  line1: string;
  line2?: string;
  lng: number;
  postalCode: string;
  state: string;
}
