/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdjustmentRequest {
  amountCents?: number;
  bookingId?: string;
  customerId: string;
  reason: string;
  tripId?: string;
}
