/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCustomerSummary {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  phone?: string;
  status?: 'ACTIVE' | 'SUSPENDED' | 'DEACTIVATED';
  verificationStatus?: 'UNVERIFIED' | 'IN_PROGRESS' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
}
