/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCustomerDetail {
  createdAt?: string;
  dateOfBirth?: string;
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  licenseExpiresOn?: string;
  licenseNumber?: string;
  licenseState?: string;
  phone?: string;
  status?: 'ACTIVE' | 'SUSPENDED' | 'DEACTIVATED';
  stripeCustomerId?: string;
  verificationCompletedAt?: string;
  verificationStatus?: 'UNVERIFIED' | 'IN_PROGRESS' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
}
