/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AvailableClassResponse {
  classId?: string;
  countAvailable?: number;
  description?: string;
  drivetrain?: 'ICE' | 'HYBRID' | 'EV';
  luggageCapacity?: number;
  name?: string;
  representativePhotoUrl?: string;
  seats?: number;
  startingDailyRateCents?: number;
}
