/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingResponse {
  assignedVehicleId?: string;
  bookingNumber?: string;
  depositAmountCents?: number;
  depositHoldClientSecret?: string;
  dropoffAt?: string;
  dropoffInZone?: boolean;
  id?: string;
  pickupAt?: string;
  quotedTotalCents?: number;
  status?: 'PENDING_PAYMENT' | 'CONFIRMED' | 'ACTIVATED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
  vehicleClassId?: string;
}
