/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PointGeoJson } from '../models/point-geo-json';
import { PolygonGeoJson } from '../models/polygon-geo-json';
export interface CreateZoneRequest {
  boundary: PolygonGeoJson;
  center: PointGeoJson;
  name: string;
  outOfZoneDropoffAllowed?: boolean;
  outOfZoneDropoffFeeCents?: number;
  slug: string;
}
