/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateRateRequest {
  dailyRateCents?: number;
  deliveryFeeCents?: number;
  effectiveFrom?: string;
  insuranceDailyCents?: number;
  insuranceTier: string;
  outOfZoneDropoffFeeCents?: number;
  vehicleClassId: string;
}
