/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePromoRequest {
  code: string;
  discountType: string;
  discountValue?: number;
  expiresAt?: string;
  maxUses?: number;
  startsAt?: string;
}
