/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBookingRequest {
  dropoffAddress?: string;
  dropoffLat: number;
  dropoffLng: number;
  paymentMethodId?: string;
  pickupAddress?: string;
  pickupLat: number;
  pickupLng: number;
  quoteId: string;
}
