/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateVehicleRequest {
  acquiredOn: string;
  classId: string;
  color: string;
  homeZoneId: string;
  licensePlate: string;
  licenseState: string;
  make: string;
  model: string;
  telematicsProvider?: string;
  telematicsVehicleId?: string;
  vin: string;
  year?: number;
}
