/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateVehicleClassRequest {
  baseDailyRateCents?: number;
  description?: string;
  drivetrain: 'ICE' | 'HYBRID' | 'EV';
  luggageCapacity?: number;
  name: string;
  seats?: number;
  sortOrder?: number;
}
