/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerReportRequest {
  description: string;
  occurredAt?: string;
  type: 'DAMAGE' | 'OUT_OF_ZONE' | 'LATE_RETURN' | 'ACCIDENT' | 'TICKET' | 'OTHER';
}
