/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncidentResponse {
  chargedAmountCents?: number;
  customerId?: string;
  id?: string;
  severity?: 'LOW' | 'MEDIUM' | 'HIGH';
  status?: 'OPEN' | 'IN_REVIEW' | 'RESOLVED' | 'DISMISSED';
  tripId?: string;
  type?: 'DAMAGE' | 'OUT_OF_ZONE' | 'LATE_RETURN' | 'ACCIDENT' | 'TICKET' | 'OTHER';
  vehicleId?: string;
}
