/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoView } from '../models/photo-view';
export interface InspectionResponse {
  fuelChargePercent?: number;
  id?: string;
  odometerMiles?: number;
  phase?: 'PICKUP' | 'DROPOFF';
  photos?: Array<PhotoView>;
  reviewStatus?: 'PASSED' | 'FLAGGED';
  tripId?: string;
}
