/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LedgerEntryView {
  amountCents?: number;
  currency?: string;
  description?: string;
  entryType?:
    | 'DEPOSIT_HELD'
    | 'DEPOSIT_CAPTURED'
    | 'DEPOSIT_RELEASED'
    | 'RENTAL_CHARGED'
    | 'OVERAGE_CHARGED'
    | 'INCIDENT_CHARGED'
    | 'REFUND_ISSUED'
    | 'DISPUTE_CHARGEBACK'
    | 'MANUAL_ADJUSTMENT';
  id?: string;
  occurredAt?: string;
}
