/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingResponse } from '../models/booking-response';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageBookingResponse {
  content?: Array<BookingResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: Array<SortObject>;
  totalElements?: number;
  totalPages?: number;
}
