/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IncidentResponse } from '../models/incident-response';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageIncidentResponse {
  content?: Array<IncidentResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: Array<SortObject>;
  totalElements?: number;
  totalPages?: number;
}
