/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminCustomerSummary } from '../models/admin-customer-summary';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageAdminCustomerSummary {
  content?: Array<AdminCustomerSummary>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: Array<SortObject>;
  totalElements?: number;
  totalPages?: number;
}
