/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LedgerEntryView } from '../models/ledger-entry-view';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageLedgerEntryView {
  content?: Array<LedgerEntryView>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: Array<SortObject>;
  totalElements?: number;
  totalPages?: number;
}
