/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentMethodResponse {
  brand?: string;
  expMonth?: number;
  expYear?: number;
  id?: string;
  isDefault?: boolean;
  last4?: string;
}
