/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoView {
  angle?: 'FRONT' | 'BACK' | 'LEFT' | 'RIGHT' | 'INTERIOR_FRONT' | 'INTERIOR_REAR' | 'ODOMETER';
  url?: string;
}
