/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoSubmission {
  angle: 'FRONT' | 'BACK' | 'LEFT' | 'RIGHT' | 'INTERIOR_FRONT' | 'INTERIOR_REAR' | 'ODOMETER';
  capturedAt?: string;
  fileSizeBytes?: number;
  heightPx?: number;
  lat?: number;
  lng?: number;
  url: string;
  widthPx?: number;
}
