/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LineItem } from '../models/line-item';
export interface QuoteResponse {
  depositCents?: number;
  discountCents?: number;
  dropoffInZone?: boolean;
  expiresAt?: string;
  lineItems?: Array<LineItem>;
  quoteId?: string;
  subtotalCents?: number;
  taxCents?: number;
  totalCents?: number;
}
