/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuoteRequest {
  dropoffAt: string;
  dropoffLat: number;
  dropoffLng: number;
  insuranceTier?: string;
  pickupAt: string;
  pickupLat: number;
  pickupLng: number;
  promoCode?: string;
  vehicleClassId: string;
}
