/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  dateOfBirth: string;
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  phone: string;
}
