/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffProfileResponse {
  id?: string;
  role?: 'ADMIN' | 'DISPATCHER' | 'SUPPORT' | 'READONLY' | 'CUSTOMER';
  username?: string;
}
