/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffCreateRequest {
  customerId?: string;
  description: string;
  occurredAt?: string;
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  tripId?: string;
  type: 'DAMAGE' | 'OUT_OF_ZONE' | 'LATE_RETURN' | 'ACCIDENT' | 'TICKET' | 'OTHER';
  vehicleId: string;
}
