/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoSubmission } from '../models/photo-submission';
export interface SubmitInspectionRequest {
  fuelChargePercent?: number;
  notes?: string;
  odometerMiles?: number;
  photos: Array<PhotoSubmission>;
}
