/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TokenResponse {
  accessToken?: string;
  expiresIn?: number;
  refreshToken?: string;
  tokenType?: string;
}
