/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransitionStatusRequest {
  status:
    | 'AVAILABLE'
    | 'RESERVED'
    | 'IN_PREPARATION'
    | 'EN_ROUTE_TO_CUSTOMER'
    | 'WITH_CUSTOMER'
    | 'EN_ROUTE_TO_WAREHOUSE'
    | 'AWAITING_INSPECTION'
    | 'IN_CLEANING'
    | 'IN_MAINTENANCE'
    | 'OUT_OF_SERVICE'
    | 'RETIRED';
}
