/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TripResponse {
  actualDropoffAt?: string;
  actualPickupAt?: string;
  bookingId?: string;
  finalChargesCents?: number;
  id?: string;
  milesDriven?: number;
  odometerEnd?: number;
  odometerStart?: number;
  status?: 'IN_PROGRESS' | 'ENDED_PENDING_INSPECTION' | 'CLOSED';
  vehicleId?: string;
}
