/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateIncidentRequest {
  chargedAmountCents?: number;
  resolutionNotes?: string;
  status?: 'OPEN' | 'IN_REVIEW' | 'RESOLVED' | 'DISMISSED';
}
