/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateZoneRequest {
  active?: boolean;
  outOfZoneDropoffAllowed?: boolean;
  outOfZoneDropoffFeeCents?: number;
}
