/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateVehicleClassRequest {
  active?: boolean;
  baseDailyRateCents?: number;
  description?: string;
  sortOrder?: number;
}
