/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleResponse {
  acquiredOn?: string;
  classId?: string;
  color?: string;
  currentAddress?: string;
  fuelChargePercent?: number;
  homeZoneId?: string;
  id?: string;
  lat?: number;
  licensePlate?: string;
  licenseState?: string;
  lng?: number;
  make?: string;
  model?: string;
  odometerMiles?: number;
  rangeMiles?: number;
  retiredOn?: string;
  status?:
    | 'AVAILABLE'
    | 'RESERVED'
    | 'IN_PREPARATION'
    | 'EN_ROUTE_TO_CUSTOMER'
    | 'WITH_CUSTOMER'
    | 'EN_ROUTE_TO_WAREHOUSE'
    | 'AWAITING_INSPECTION'
    | 'IN_CLEANING'
    | 'IN_MAINTENANCE'
    | 'OUT_OF_SERVICE'
    | 'RETIRED';
  telematicsProvider?: string;
  vin?: string;
  year?: number;
}
