/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleClassResponse {
  active?: boolean;
  baseDailyRateCents?: number;
  description?: string;
  drivetrain?: 'ICE' | 'HYBRID' | 'EV';
  id?: string;
  luggageCapacity?: number;
  name?: string;
  seats?: number;
  sortOrder?: number;
}
