/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleClass {
  active?: boolean;

  /**
   * Integer minor units (cents)
   */
  baseDailyRate: number;
  currency: string;
  description?: string;
  drivetrain?: string;
  id: string;
  luggage?: number;
  name: string;
  seats?: number;
}
