/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerificationResponse {
  clientSecret?: string;
  completedAt?: string;
  sessionId?: string;
  status?: 'CREATED' | 'PROCESSING' | 'VERIFIED' | 'REQUIRES_INPUT' | 'CANCELED';
}
