/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PointGeoJson } from '../models/point-geo-json';
import { PolygonGeoJson } from '../models/polygon-geo-json';
export interface ZoneResponse {
  active?: boolean;
  boundary?: PolygonGeoJson;
  center?: PointGeoJson;
  id?: string;
  name?: string;
  outOfZoneDropoffAllowed?: boolean;
  outOfZoneDropoffFeeCents?: number;
  slug?: string;
}
