/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AttachPaymentMethodRequest } from '../../models/attach-payment-method-request';
import { PaymentMethodResponse } from '../../models/payment-method-response';

export interface Attach$Params {
  body: AttachPaymentMethodRequest;
}

export function attach(
  http: HttpClient,
  rootUrl: string,
  params: Attach$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PaymentMethodResponse>> {
  const rb = new RequestBuilder(rootUrl, attach.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentMethodResponse>;
    }),
  );
}

attach.PATH = '/api/customer/me/payment-methods';
