/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerProfileResponse } from '../../models/customer-profile-response';

export interface Me$Params {}

export function me(
  http: HttpClient,
  rootUrl: string,
  params?: Me$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<CustomerProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, me.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerProfileResponse>;
    }),
  );
}

me.PATH = '/api/customer/me';
