/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerificationResponse } from '../../models/verification-response';

export interface Start$Params {}

export function start(
  http: HttpClient,
  rootUrl: string,
  params?: Start$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VerificationResponse>> {
  const rb = new RequestBuilder(rootUrl, start.PATH, 'post');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerificationResponse>;
    }),
  );
}

start.PATH = '/api/customer/me/verification';
