/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerProfileResponse } from '../../models/customer-profile-response';
import { UpdateProfileRequest } from '../../models/update-profile-request';

export interface Update$Params {
  body: UpdateProfileRequest;
}

export function update(
  http: HttpClient,
  rootUrl: string,
  params: Update$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<CustomerProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, update.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerProfileResponse>;
    }),
  );
}

update.PATH = '/api/customer/me';
