/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageLedgerEntryView } from '../../models/page-ledger-entry-view';

export interface ByCustomer$Params {
  customerId: string;
  pageable: Pageable;
}

export function byCustomer(
  http: HttpClient,
  rootUrl: string,
  params: ByCustomer$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PageLedgerEntryView>> {
  const rb = new RequestBuilder(rootUrl, byCustomer.PATH, 'get');
  if (params) {
    rb.path('customerId', params.customerId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageLedgerEntryView>;
    }),
  );
}

byCustomer.PATH = '/api/admin/ledger/customers/{customerId}';
