/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LedgerEntryView } from '../../models/ledger-entry-view';

export interface ByTrip$Params {
  tripId: string;
}

export function byTrip(
  http: HttpClient,
  rootUrl: string,
  params: ByTrip$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<LedgerEntryView>>> {
  const rb = new RequestBuilder(rootUrl, byTrip.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LedgerEntryView>>;
    }),
  );
}

byTrip.PATH = '/api/admin/ledger/trips/{tripId}';
